@startuml
left to right direction
actor User as u
actor Member as m
actor PathFinder as p
u <|-- m
m <|-- p

package 경로(path)서비스 {
    usecase "경로 만들기" as r.uc1
    usecase "경로 수정하기" as r.uc2
    usecase "경로 삭제 하기" as r.uc3
    usecase "경로 북마크하기" as r.uc4
    usecase "경로 공유하기" as r.uc5
    usecase "경로에 댓글달기" as r.uc6
    usecase "경로 댓글에 답글달기" as r.uc7
    usecase "경로 검색하기" as r.uc8
    usecase "경로에서 footprint 제거하기" as r.uc9
    usecase "경로에 footprint 추가하기" as r.uc10
    usecase "경로에 좋아요 하기" as r.uc11
}
u --> r.uc8
m --> r.uc1
p --> r.uc2
p --> r.uc3
m --> r.uc4
p --> r.uc5
m --> r.uc6
m --> r.uc7
p --> r.uc9
p --> r.uc10
m --> r.uc11

note right of r.uc11
    하나의 경로에 한번만 가능하다.
end note

note right of r.uc4
    하나의 경로에 한번만 가능하다.
end note
@enduml
